language: python

python:
    - "2.7"

branches:
    only:
        - master

cache:
    directories:
        - $HOME/.cache/pip

sudo: false

install:
    - pip install -r requirements-travis.txt

script:
    - inspekt lint
    - inspekt indent
    - inspekt style
