language: python

python:
   - "2.7"
   - "3.3"
   - "3.4"
   - "3.5"
   - "pypy"
   - "pypy3"

install:
   - pip install flake8 pycodestyle

script:
   - flake8 --ignore=W191,F401,E501,F403,F405,E226 .
   - pycodestyle --filename=*.py --ignore=E501 --count .

notifications:
  email:
    on_success: change
    on_failure: always
