language: python

python:
   - "2.7"
   - "3.3"
   - "3.4"
   - "3.5"
   - "pypy"
   - "pypy3"

install:
   - pip install flake8 pep8 pylint

script:
   - flake8 --ignore=W191,F401,E501,F403 .
   - pep8 --filename=*.py --ignore=W293,E201,E202,E501 --count .
   - pylint -E openbsd-tests

notifications:
  email:
    on_success: change
    on_failure: always
