.\"	$Id$
.\"
.\" Copyright (c) 2020 Sergey Bronnikov
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: October 21 2020 $
.Dt RUNTEST 1
.Os
.Sh NAME
.Nm runtest
.Nd is a program for running OpenBSD regression tests.
.Sh SYNOPSIS
.Nm
.Op Fl h
.Op Fl d Ar directory
.Op Fl f Ar filter
.Op Fl l Ar list
.Op Fl t Ar timeout
.Op Fl o Ar report
.Op Fl v
.Sh DESCRIPTION
The
.Nm
executes regression tests.
The options are as follows:
.Bl -tag -width Dssmacro=value
.It Fl d
Directory where
.Nm
will search tests.
.It Fl f
Specify regular expression to filtering tests.
.It Fl l
Lists found tests.
.It Fl t
Timeout.
.It Fl o
Filename where 
.Nm
will output TAP-compliant test results.
.El
.Sh STANDARDS
.Rs
.%A M. G. Schwern, A. Lester, A. Armstrong
.%D 2003-2007
.%T TAP 13 - The Test Anything Protocol v13
.Re
.Pp
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr bsd.regress.mk 5
.Xr regex 3
.Xr make 1
.Sh AUTHORS
.An -nosplit
The
.Nm
utility was written by
.An Sergey Bronnikov
