#!/bin/sh

set -e

pkg_add afl

# tmux new-session -d 'sleep 10'
# tmux new-session -s mail -n mel_GMAIL -d "TERM=xterm-256color ; sleep 10"
# afl/bin/afl-tmin -i crash_sample.pl -o min_crash_sample.pl perl

cd /usr/src/usr.bin/doas
CC=afl-gcc make
afl-fuzz -i in -o out -f doas.conf -- ./doas -C @@ ls
# dict?

cd /usr/src/usr.sbin/acme-client
CC=afl-gcc make
acme-client -f acme-client.conf example.com
# dict?

cd /usr/src/usr.bin/cap_mkdb
CC=afl-gcc make
afl-fuzz -i in -o out -f termcap -- ./cap_mkdb -f outfile @@
# dict?

# httpd
CC=afl-gcc make
# dict?

/usr/src/sbin/dhclient
CC=afl-gcc make
afl-fuzz -i in -o out -f dhclient.conf -- ./dhclient -n -c @@ em0
# dict?

# mtree

# libfuzzer candidates:
# 	??? bin/chio
# 	??? sbin/pfctl - failed compilation
# 	??? usr.sbin/syslogd - no option check_config
# 	??? afl-fuzz -i in -o out -f termcap -- cap_mkdb/cap_mkdb -f outfile @@

# sbin/iked
# sbin/ipsecctl
# usr.bin/lex
# usr.sbin/bgpd
# usr.sbin/dvmrpd
# usr.sbin/eigrpd
# usr.sbin/hostapd
# usr.sbin/ifstated
# usr.sbin/iscsictl
# usr.sbin/ldapd
# usr.sbin/ldomctl
# usr.sbin/ldpd
# usr.sbin/npppd/npppd
# usr.sbin/ntpd
# usr.sbin/ospf6d
# usr.sbin/ospfd
# usr.sbin/radiusd
# usr.sbin/relayd
# usr.sbin/ripd
# usr.sbin/smtpd
# usr.sbin/snmpd
# usr.sbin/switchd
# usr.sbin/vmd
# usr.sbin/ypldap

# create report and save results
