#!/bin/sh

# make in parallel?

set -e

pkg_add afl

cd /usr/src/usr.bin/doas
CC=afl-gcc make
afl-fuzz -i in -o out -f doas.conf -- ./doas -C @@ ls

# bin/chio
# sbin/iked
# sbin/ipsecctl
# sbin/pfctl
# usr.bin/doas
# usr.bin/lex
# usr.sbin/acme-client
# usr.sbin/bgpd
# usr.sbin/dvmrpd
# usr.sbin/eigrpd
# usr.sbin/hostapd
# usr.sbin/httpd
# usr.sbin/ifstated
# usr.sbin/iscsictl
# usr.sbin/ldapd
# usr.sbin/ldomctl
# usr.sbin/ldpd
# usr.sbin/npppd/npppd
# usr.sbin/ntpd
# usr.sbin/ospf6d
# usr.sbin/ospfd
# usr.sbin/radiusd
# usr.sbin/relayd
# usr.sbin/ripd
# usr.sbin/smtpd
# usr.sbin/snmpd
# usr.sbin/switchd
# usr.sbin/vmd
# usr.sbin/ypldap

# afl-fuzz -i in -o out -f termcap -- cap_mkdb/cap_mkdb -f outfile @@

# create report and save results
