#!/bin/sh

# https://rhn.redhat.com/errata/
# https://access.redhat.com/security/security-updates/

set -eu

# src/sys/arch:
# alpha|amd64|amiga|arc|arm|arm32|armish|armv7|atari|aviion|beagle|
# cats|gumstix|hp300|hppa|hppa64|i386|ia64|kbus|landisk|loongson|luna88k
# m68k|m88k|mac68k|macppc|mips|mips64|moko|mvme68k|mvme88k|mvmeppc
# octeon|palm|pc532|pegasos|pica|pmax|powerpc|sgi|sh|socppc|solbourne
# sparc|sparc64|sun3|vax|wgrisc|zaurus

function patches {
   maj=$1
   min=$2
   page="https://ftp.openbsd.org/pub/OpenBSD/patches/$maj.$min/common/" 
   http_code=`curl -s -I $page | head -n 1|cut -d$' ' -f2`
   if [[ $http_code -eq "200" ]]; then
      echo "### $maj.$min [patches](https://www.openbsd.org/errata$maj$min.html)\n"
      patches=`curl -s $page | sed -n 's/.*href="\(.*patch\)".*/\1/p'`
      num=0
      for p in $patches;
      do
	    ##echo "* $p - \c"
	    num=$(($num+1))
        path=`curl -s $page/$p | sed -n 's/^Index: \(.*\)$/\1/p' | head -1`
        echo `dirname $path`
	  done
      ##echo "\n$maj.$min - $num\n"
   fi
}

for rel_maj in `seq 2 1 7`;
do
	for rel_min in `seq 0 1 9`;
	do
		patches $rel_maj $rel_min
	done
done
